# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffe44f4f33e6a39d68e1b61608dd8ca57653f35f5df473df0b1951c3876ff0b44e126253060fba67a659811744fda566bd7b92f69ff1b7791992f9736df14097

test:
  secret_key_base: c10bcc1fae79f34bb4aa1b9ac1c190cd384d1f79062e4db059d94f54a24022ea32518732831f34e0dec217b7b1874a51b69ab3468eda1aa557b0a0be2116cab2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
